Match_the_Boxes game added
chimple/jamaica pull request #20
Opened 2019-02-28 05:53 UTC by Manukumar1995

2019-03-01 07:51 UTC, talapadi requested changes

2019-03-01 07:51 UTC, talapadi commented on lib/games/box_matching_game.dart
> +  List<List<String>> addToBox = [[], [], [], []];
Why is this hardcoded to 4?

2019-03-01 08:31 UTC, Manukumar1995 commented on lib/games/box_matching_game.dart
> +  List<List<String>> addToBox = [[], [], [], []];
changes added

2019-03-05 03:24 UTC, talapadi requested changes

2019-03-05 03:24 UTC, talapadi commented on lib/games/box_matching_game.dart
> +class MatchTheBoxGame extends StatefulWidget {
Make sure the file name and the class name match

2019-03-05 06:11 UTC, merged