added crossword game
chimple/jamaica pull request #23
Opened 2019-03-01 08:35 UTC by nikhil-chimple

2019-03-05 03:26 UTC, talapadi requested changes

2019-03-05 03:26 UTC, talapadi commented on lib/games/crossword_game.dart
> +  var random = new Random();
do you need this?

2019-03-05 03:26 UTC, talapadi commented on lib/games/crossword_game.dart
> +      rows: cols>choiceDetails.length?1:2,
space the words properly

2019-03-06 04:43 UTC, nikhil-chimple commented on lib/games/crossword_game.dart
> +      rows: cols>choiceDetails.length?1:2,
its done boss

2019-03-06 05:40 UTC, merged